export const techDict: Record<string, string> = {
  NextJS: "https://nextjs.org/",
  Codegen: "https://www.graphql-codegen.com/",
  TypeScript: "https://www.typescriptlang.org/",
  NodeJS: "https://nodejs.org/",
  GraphQL: "https://graphql.org/",
  "Prisma ORM": "https://www.prisma.io/",
  PostgreSQL: "https://www.postgresql.org/",
  Redis: "https://redis.io/",
  AWS: "https://aws.amazon.com/",
  ReactJS: "https://reactjs.org/",
  TailwindCSS: "https://tailwindcss.com/",
  NextAuth: "https://next-auth.js.org/",
  MongoDB: "https://www.mongodb.com/",
  ExpressJS: "https://expressjs.com/",
  ChartJS: "https://www.chartjs.org/",
  Java: "https://www.java.com/",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  SQL: "https://www.sql.org/",
  Git: "https://git-scm.com/",
};
